name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#42a5f5"
  image: "assets/icon/app_icon.png"

  android_12:
    image: "assets/icon/app_icon.png"
    icon_background_color: "#42a5f5"
    image_dark: "assets/icon/app_icon.png"
    icon_background_color_dark: "#42a5f5"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
